### ISSUE TITLE
It looks like something went wrong

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/file-drop#15]
https://github.com/GoogleChromeLabs/file-drop/tree/master/lib where's all the code?

**Comment by PaulKinlan** [comment]
I'm not sure ... Surma did a change to change the entry points....

**Comment by PaulKinlan** [comment]
For whatever reason, I made a big boo-boo, and when we looked at Surma's code on his machine it was cool, then I didn't review it thoroughly when I merged it. Reverted.
