### ISSUE TITLE
Allow 'accept' to be omitted

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/file-drop#3]
If omitted it should consider every file valid. This is what we need to do with Squoosh.

The drag & drop API derives types from file extension, but we're (and the browser is) a bit smarter than that. We sniff the file, so we can load the image even if the extension's wrong. Whereas file-drop will return invalid for an invalid extension.

This is especially important as most browsers to not consider `whatever.webp` an image, as they don't recognise `*.webp`.

**Comment by PaulKinlan** [comment]
I actually saw this in the test - will sort.
